name: Auto-doc (Action)
on:
  pull_request:
    branches: [ main]
    paths:
      - action.yml
      - README.md
permissions:
  contents: write
  pull-requests: write
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  update-docs:
    if: github.event.pull_request.head.repo.full_name == github.repository
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: tj-actions/auto-doc@v3
        with:
          filename: action.yml
          output: README.md
          reusable: false
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "docs: sync README with action.yml"
  verify-docs:
    if: github.event.pull_request.head.repo.full_name != github.repository
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: tj-actions/auto-doc@v3
        with:
          filename: action.yml
          output: README.md
          reusable: false
      - run: git diff --exit-code
